const campuses = [
  ['AI للإيميلات', 'تكتب ردودًا مهنية، تلخص السلاسل الطويلة، وتجهز المتابعة بنبرة عملك.', '✉️'],
  ['AI للتقارير', 'تحول الملاحظات والبيانات إلى ملخص تنفيذي ومخاطر وقرارات مطلوبة.', '📊'],
  ['AI للاجتماعات', 'تستخرج القرارات والمهام والمتابعات بدل ضياع النقاش في التسجيلات.', '🎙️'],
  ['AI للعروض', 'تبني عرضًا تنفيذيًا من فكرة أو ملف أو تقرير بسرعة وجودة أعلى.', '🖥️'],
  ['AI لمراجعة الملفات', 'تراجع النواقص والأخطاء قبل إرسالها لمديرك أو عميلك.', '🧾'],
  ['AI للمتابعة', 'تحول الفوضى اليومية إلى قائمة مهام ورسائل متابعة واضحة.', '✅'],
  ['شهادات مهنية', 'نساعدك تختار مسارات وشهادات من منصات تعليمية موثوقة تضيفها لملفك.', '🎓'],
  ['مشروع عملي', 'كل تعلم ينتهي بمساعد أو أتمتة قابلة للاستخدام في وظيفتك.', '⚙️'],
];
const wins = [
  ['/proof/reem-claude-fast.png', 'ريم', 'تعلم Claude بسرعة'],
  ['/proof/khalid-app-2-weeks.png', 'خالد', 'بناء تطبيق خلال أسبوعين'],
  ['/proof/abdulwahab-automation-certificate.png', 'عبدالوهاب', 'تعلم الأتمتة مع شهادة'],
];
const faqs = [
  ['هل أحتاج خبرة تقنية؟', 'لا. تبدأ من مهمة واضحة في وظيفتك، ثم تستخدم أدوات AI بخطوات عملية وبشرح عربي.'],
  ['هل هذا مجرد برومبتات؟', 'لا. البرومبت جزء صغير. الأهم أن تتحول مهامك إلى مساعدين ومخرجات متكررة قابلة للمراجعة.'],
  ['هل الشهادات منكم؟', 'المجلس يساعدك تختار وتنجز مسارات من منصات تعليمية موثوقة. لا ندّعي اعتمادًا رسميًا للمجلس نفسه إلا إذا ذُكر اسم الجهة بوضوح.'],
  ['ماذا أفعل أول أسبوع؟', 'تختار مهمة من وظيفتك، تبني مساعدًا لها، وتحدد مسار شهادة مناسب يثبت مهارتك.'],
  ['هل يناسب المديرين والموظفين؟', 'نعم إذا لديك تقارير، اجتماعات، مراجعة ملفات، رسائل، عروض، أو قرارات تحتاج سرعة وجودة أعلى.'],
  ['متى أرى نتيجة؟', 'الهدف أن تخرج بأول مساعد عملي خلال 7 أيام، ثم تبني ملف مهارات وشهادات مع الوقت.'],
];
function CTA({ children = 'انضم الآن' }: { children?: string }) { return <a className="cta" href="#checkout">{children}<span>←</span></a>; }
function ProofLine() { return <div className="proofLine"><div className="faces"><i/><i/><i/><i/></div><span>30+ تنفيذي ومدير سعودي · مئات الموظفين في الخليج · AI عملي للوظيفة لا للترند</span></div>; }
export default function Page() {
  return <main>
    <nav className="nav"><a className="brand" href="#top"><span className="logoWrap"><img src="/atmatha-logo.png" alt="أتمتها" /></span><span>مجلس الأتمتة+</span></a><div className="navLinks"><a href="#method">الخطر</a><a href="#campuses">المهارات</a><a href="#wins">الإثبات</a><a href="#checkout">الاشتراك</a></div><CTA>ابدأ الآن</CTA></nav>
    <section className="hero" id="top"><div className="heroLight"/><div className="container heroGrid"><div className="heroCopy"><div className="micro">THE AI WORK SURVIVAL MAJLIS</div><h1>لا تكن الموظف<br/><span>الذي يستبدله AI.</span><br/>كن الموظف الذي يستخدمه.</h1><p>مجلس الأتمتة+ للمحترفين الذين يريدون حماية قيمتهم في سوق العمل: تتعلم AI داخل وظيفتك، تبني مساعدين لمهامك اليومية، وتجمع شهادات مهنية من منصات تعليمية موثوقة تقوي ملفك.</p><div className="heroActions"><CTA>ابدأ مهارة AI تثبتها هذا الأسبوع</CTA><a className="ghost" href="#method">افهم الخطر</a></div><ProofLine/></div><div className="heroVisual"><div className="videoShell"><img src="/osama-portrait.jpg" alt="أسامة الكلثمي في فعالية"/><div className="play">▶</div><div className="videoText"><b>الوظيفة لن تبقى كما هي.</b><span>مهمة عمل → مساعد AI → شهادة مهنية → قيمة أعلى</span></div></div><div className="notice n1"><b>7 أيام</b><span>أول مساعد ذكي</span></div></div></div></section>
    <section className="ticker"><div><span>AI داخل وظيفتك</span><span>شهادات مهنية</span><span>مساعد ذكي</span><span>مشروع عملي</span><span>ترقية مهارية</span><span>ملف أقوى</span><span>AI داخل وظيفتك</span><span>أتمتة</span><span>مساعد ذكي</span></div></section>
    <section className="proofStats container"><div><strong>30+</strong><span>تنفيذي ومدير سعودي</span></div><div><strong>100s</strong><span>موظفين في الخليج</span></div><div><strong>7 أيام</strong><span>أول مساعد عملي</span></div><div><strong>كل أسبوع</strong><span>لايف ومراجعة وشهادات</span></div></section>
    <section className="section container" id="method"><div className="sectionIntro"><small>THE ENEMY</small><h2>الخطر ليس أن AI موجود. الخطر أن زميلك سيتعلمه قبلك.</h2><p>الشركات لن تكافئ من يراقب التغيير من بعيد. ستكافئ الموظف الذي يستخدم AI ليخرج تقارير أسرع، عروض أوضح، قرارات أدق، ومهارات موثقة.</p></div><div className="versus"><article className="path bad"><small>خارج المجلس</small><h3>تتفرج على موجة AI</h3><ul><li>مقاطع كثيرة بلا تطبيق وظيفي.</li><li>خوف من الاستبدال بدون خطة.</li><li>برومبتات لا تثبت مهارة.</li><li>لا يوجد ملف إنجاز أو شهادة.</li></ul></article><article className="path good"><small>داخل المجلس</small><h3>تصير موظف AI-enabled</h3><ul><li>تختار مهمة من عملك.</li><li>تبني لها مساعدًا عمليًا.</li><li>تتعلم مسار شهادة مناسب.</li><li>تضيف إنجازًا واضحًا لملفك.</li></ul></article></div></section>
    <section className="phaseSection"><div className="container"><div className="sectionIntro centered"><small>3-PHASE CAREER UPGRADE</small><h2>من موظف مهدد بالتغيير إلى موظف يستخدم AI بوضوح.</h2></div><div className="phases"><div><span>STEP 1</span><h3>اختر مهمة من وظيفتك</h3><p>تقرير، إيميل، عرض، اجتماع، مراجعة ملف، أو متابعة يومية.</p></div><div><span>STEP 2</span><h3>ابنِ مساعد AI</h3><p>استخدم قالبًا جاهزًا، ثم أضف سياق عملك وطريقة مخرجاتك.</p></div><div><span>STEP 3</span><h3>وثّق المهارة</h3><p>راجع المخرج، ثم ادخل مسار شهادة أو دبلوم قصير من منصة موثوقة.</p></div></div><CTA>ابدأ ترقية مهارتك</CTA><ProofLine/></div></section>
    <section className="section container" id="campuses"><div className="sectionIntro"><small>AI WORK SKILLS</small><h2>تعلم AI حيث يهم فعلًا: داخل وظيفتك.</h2><p>كل مهارة هنا مرتبطة بمهمة عمل، مخرج قابل للاستخدام، ومسار يوثق تطورك المهني.</p></div><div className="campusGrid">{campuses.map(([title, body, icon]) => <article className="campus" key={title}><div className="campusIcon">{icon}</div><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="appShowcase"><div className="container appGrid"><div className="assetFrame"><img src="/generated/gold-scene.svg" alt="خلفية واجهة مساعد ذكي"/><div className="appMock"><div className="appTop"><i/><i/><i/></div><div className="chat mine">جهّز تقريرًا أسبوعيًا من هذه الملاحظات.</div><div className="chat ai">سأقسمه إلى ملخص تنفيذي، مؤشرات، مخاطر، وقرارات مطلوبة.</div><div className="report"><b>مخرج جاهز</b><span>تقرير مرتب + مهام متابعة + نقاط قرار</span></div></div></div><div className="appCopy"><small>CERTIFIED GROWTH PATH</small><h2>لا تجمع معلومات. اجمع مهارات تثبتها في عملك.</h2><p>الفكرة ليست أن تشاهد كورسات AI فقط. الفكرة أن تطبق AI على مهمة حقيقية، تعرض نتيجة، ثم تختار شهادة مهنية من منصة موثوقة تقوي ملفك الوظيفي.</p><CTA>ادخل المجلس</CTA><ProofLine/></div></div></section>
    <section className="section container" id="wins"><div className="sectionIntro centered"><small>REAL WINS</small><h2>إثبات أن الناس تتعلم وتطبق، لا تشاهد فقط.</h2><p>لقطات حقيقية لأعضاء تعلموا أدوات، بنوا مشاريع، وبدأوا يربطون AI بمسارهم المهني.</p></div><div className="wins">{wins.map(([src, name, result]) => <article className="win" key={src}><img src={src} alt={`${name} - ${result}`}/><div><b>{name}</b><span>{result}</span></div></article>)}</div></section>
    <section className="choice"><div className="container choiceGrid"><div className="choiceCard muted"><small>THEIR WAY</small><h3>تنتظر حتى تصبح مهارتك قديمة</h3><p>تستهلك أخبار AI ومقاطع كثيرة بينما وظيفتك تتغير أسرع منك.</p><a href="https://www.youtube.com/">استمر في المشاهدة</a></div><div className="vs">VS</div><div className="choiceCard active"><small>OUR WAY</small><h3>تدخل موجة AI من داخل عملك</h3><p>تبدأ بمهمة حقيقية، تبني مساعدًا لها، وتتابع مسار شهادة يقوي ملفك.</p><CTA>انضم الآن</CTA></div></div></section>
    <section className="checkout" id="checkout"><div className="container checkoutGrid"><div className="priceBox"><small>CHOOSE YOUR PATH</small><h2>$80</h2><p>شهريًا — استثمار صغير مقارنة بخسارة قيمتك المهنية إذا أصبحت مهاراتك قديمة أمام AI.</p><CTA>انضم إلى مجلس الأتمتة+</CTA><ProofLine/></div><div className="stack"><h3>ما الذي تحصل عليه؟</h3><ul><li>تطبيق AI على مهام وظيفية حقيقية.</li><li>قوالب ومساعدات قابلة للتعديل حسب دورك.</li><li>توجيه لاختيار شهادات من منصات تعليمية موثوقة.</li><li>مجتمع ولايف أسبوعي ومراجعة تطبيق.</li></ul></div></div></section>
    <section className="section container" id="faq"><div className="sectionIntro centered"><small>FAQ</small><h2>أسئلة قبل الانضمام</h2></div><div className="faqGrid">{faqs.map(([q,a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
    <section className="final"><div className="container"><h2>AI سيغيّر وظيفتك. السؤال: هل ستكون جاهزًا؟</h2><p>ادخل بمهمة واحدة من عملك. اخرج بمساعد ذكي، وخطة مهارة، ومسار شهادة يثبت أنك تطورت.</p><CTA>ابدأ هذا الأسبوع</CTA><ProofLine/></div></section>
    <footer>مجلس الأتمتة+ — تعلم AI داخل وظيفتك، ابنِ مساعدين عمليين، وقوِّ ملفك المهني.</footer><div className="mobileSticky"><CTA>انضم الآن — 80 دولار شهريًا</CTA></div>
  </main>;
}
